### ISSUE TITLE
Call for validation of Random implementation

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/roadrunner#564] opened 2019-08-01 00:56 UTC
Originally discussed in https://github.com/sys-bio/tellurium/issues/391#issuecomment-516214611, I would like to call for a validation of how Random object is implemented in libRoadRunner. 

> When using the initial implementation, e.g.:
> ```
> double distrib_uniform_ast(double _min, double _max)
> {
>     std::random_device rd;
>     cxx11_ns::mt19937 engine(rd());
>  #ifdef CXX11_RANDOM
>     cxx11_ns::uniform_real_distribution<double> dist(_min, _max);
> #else
>     cxx11_ns::uniform_real<double> dist(_min, _max);
> #endif
>     return dist(engine);
> }
> ```
> I get the following histogram:
> ![image](https://user-images.githubusercontent.com/7672320/62091799-984a8500-b227-11e9-8a11-9e2de7087018.png)
> which seems okay.
> 
> However, when I use `Random` object, e.g.:
> ```
> double distrib_uniform(Random *random, double _min, double _max)
> {
>     Log(Logger::LOG_DEBUG) << "distrib_uniform("
>             << static_cast<void*>(random)
>             << ", " << _min << ", " << _max << ")";
> 
> #ifdef CXX11_RANDOM
>     cxx11_ns::uniform_real_distribution<double> dist(_min, _max);
> #else
>     cxx11_ns::uniform_real<double> dist(_min, _max);
> #endif
>     return dist(*random);
> }
> ```
> I get this:
> ![image](https://user-images.githubusercontent.com/7672320/62091899-fe370c80-b227-11e9-8c58-8130d9f371da.png)
> As I said, this behavior is observed even in older versions of libRoadRunner. There is some serious flaw with how distrib was implemented I think.

Few areas of concern:

1) Throughout the source, a `LLVMModelData` object and a `llvm::Value` object are all initialized under the name of `modelData`.  Only `llvm::Value` object with `modelData` name gets passed around downstream. What is going on? `LLVMModelData` object seems to have the fieldname for `RandomPtr`.

2) Where is `llvm::Value modelData` getting initialized? [This file](https://github.com/sys-bio/roadrunner/blob/develop/source/llvm/CodeGenBase.h) seems to do it but not sure.

@luciansmith also provided a test suite we can use at https://github.com/luciansmith/stochastic-distrib-test-suite.

**Comment by luciansmith** [comment] 2019-08-01 03:08
What's the X axis?  I'm not sure what I'm looking at.

**Comment by kirichoi** [comment] 2019-08-01 03:16
The plots are histograms (or approximation of probability density functions). For uniform distribution, you want a square, for normal distribution, a Gaussian function, etc. I am seeing a weird trend where sampled distribution does not approximate to probability density functions.

**Comment by luciansmith** [comment] 2019-08-01 04:41
So, it's supposed to be a uniform distribution, but looks like a normal instead.  That is indeed a problem!

I guess the issue with the Random object is that this is how to get a seed to persist?

If it helps, many years ago, when I was developing a stochastic test for SBML, Frank implemented something in roadrunner to let it take a seed and use that.  However, it ended up failing my tests, because it would pick the same number (or very similar numbers) several times in a row (or, to put it another way, the autocorrelation was too high).  That sort of looks like the same problem you're having?  I don't suppose there's an autocorrelation value in Random that you need to set to zero?

**Comment by evilnose** [comment] 2020-04-24 21:52
I've pushed some changes to `ast-distrib` that fixes the distribution issue. As it took me quite a while to find the cause, I'll post a comment here in case someone encounters a similar problem in the future.

The issue is due to the difference between `engine` and `random`. `engine` is a Uniform Random Bit Generator (URBG), whose result is passed to distributions like `uniform_real` and `exponential_distribution`, which in turn generate a real/int following a particular distribution. On the other hand, `Random` generates a uniformly distributed double from 0 to 1, _using_ the input of a URBG.

So in this case `*random` should not be passed to `dist`, because `dist` expects uniformly distributed bits whereas `random` generates a uniformly distributed double. The bell-shape likely has to do with the bit representation of doubles.

It is confusing that while `engine` (of type `mt19937`) and `random` have the same interface (i.e. `min()`, `max()`, `operator::()()`), they have quite different usage. More on this at https://en.cppreference.com/w/cpp/numeric/random

**Comment by luciansmith** [comment] 2020-05-04 17:05
This fix is now merged into develop with https://github.com/sys-bio/roadrunner/pull/561

**Closed as completed by luciansmith** 2020-05-04 17:05 UTC
Labels: bug, enhancement, help wanted, priority
