### ISSUE TITLE
roadrunner crash on simple model

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#682] opened 2020-09-29 18:30 UTC
Run this model and roadrunner crashes with an unknown exception:

Running:

[('tellurium', '2.1.6'),
 ('roadrunner', '2.0.0'),
 ('antimony', '2.12.0.3'),
 ('libsbml', '5.18.1'),
 ('libsedml', '0.4.52'),
 ('phrasedml', '1.0.10'),
 ('pySBOL', '2.3.2')]

import tellurium as te
import roadrunner

r = te.loada("""
    A -> B; v;
    2 B -> A; v;
""")

runfile('D:/Documents/Tellurium/ISGSB_2020/untitled50.py', wdir='D:/Documents/Tellurium/ISGSB_2020')
Traceback (most recent call last):

  File "D:\Documents\Tellurium\ISGSB_2020\untitled50.py", line 14, in <module>
    """)

  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\tellurium\tellurium.py", line 517, in loada
    return loadAntimonyModel(ant)

  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\tellurium\tellurium.py", line 534, in loadAntimonyModel
    return roadrunner.RoadRunner(sbml)

  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\tellurium\roadrunner\extended_roadrunner.py", line 16, in __init__
    super(ExtendedRoadRunner, self).__init__(*args, **kwargs)

  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\roadrunner\roadrunner.py", line 3768, in _new_init
    RoadRunner._swig_init(self, *args)

  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\roadrunner\roadrunner.py", line 2524, in __init__
    this = _roadrunner.new_RoadRunner(*args)

RuntimeError: Unknown exception

**Comment by luciansmith** [comment] 2020-10-22 23:30
This turns out to be a duplicate of https://github.com/sys-bio/roadrunner/issues/685 : the 'v' parameter is uninitialized, and roadrunner refuses to proceed.

**Closed as completed by luciansmith** 2020-10-22 23:30 UTC
Labels: bug, priority
