### ISSUE TITLE
non deterministic behaviour when using multiple assigment operators

### ISSUE THREAD

**Issue by steffenger** [sys-bio/roadrunner#976] opened 2022-03-23 15:21 UTC
Hi all,

I am working together with @matthiaskoenig on the application described in #973. 
I tried checkpointing using a small example:

    `rr:: RoadRunner roadrunner(model_path);

    //create copy for checkpoint
    rr::RoadRunner roadrunnerB;
   
    // save checkpoint
    roadrunnerB = roadrunner;
    
    roadrunner.oneStep(t_start, delta_time);
    std::cout << "apap_ext: " << roadrunner.getValue("[apap_ext]") << std::endl;

    //go back to checkpoint if FEM did not converged
    roadrunner = roadrunnerB;
    
    //rerun with smaller timestep
    roadrunner.oneStep(t_start, (delta_time/2));

    std::cout << "apap_ext: " << roadrunner.getValue("[apap_ext]") << std::endl; `

    

Sometimes the simulation is successful and sometimes this weird error comes:

![image](https://user-images.githubusercontent.com/95339856/159729558-b806ee68-5554-47e0-9949-a03754006eb9.png)

This could also be the reason why we have problems with the coupling between RoadRunner and the macro FEM simulation.
Do you have any idea how to avoid this error?

If you need more information please let me know.

best regards,

steffen

**Comment by luciansmith** [comment] 2022-03-24 01:12
Well, the good news is that I can reproduce the problem (thanks for the code!) and the bad news is that it is mystifying me.  I'll let you know when I figure something out!

I can at least say that when I use saveStateS and loadStateS instead of '=', I don't have a problem, if you need something to tide you over in the meantime...

**Comment by steffenger** [comment] 2022-03-24 08:31
@luciansmith thanks for the quick answer, it is mystifying me as well:)
I have already tried a workaround with save/loadStateS.


    `//save State for checkpoint
    std::stringstream* roadrunner_state = roadrunner.saveStateS();

    roadrunner.oneStep(t_start, delta_time);
    std::cout << "apap_ext: " << roadrunner.getValue("[apap_ext]") << std::endl;

    //go back to checkpoint if FEM did not converged
    roadrunner.loadStateS(roadrunner_state);
    
    //save State again
    std::stringstream* roadrunner_state2 = roadrunner.saveStateS();

    //rerun with smaller timestep
    roadrunner.oneStep(t_start, (delta_time/2));

    std::cout << "apap_ext: " << roadrunner.getValue("[apap_ext]") << std::endl;

    //go back to checkpoint if FEM did not converged
    roadrunner.loadStateS(roadrunner_state2);

    //rerun with smaller timestep
    roadrunner.oneStep(t_start, (delta_time/4));

    std::cout << "apap_ext: " << roadrunner.getValue("[apap_ext]") << std::endl;`

*I think there is also no way for using just one stringstream roadrunner_state
The funny thing is that it works for one rerun but for multiple reruns I get a similiar problem.

![image](https://user-images.githubusercontent.com/95339856/159872581-fefe54fa-d638-4cbf-a52e-1a7f12a6c1e6.png)

I also wonder if this is generally due to roadrunner or due to LLVM.

**Comment by luciansmith** [comment] 2022-03-24 22:11
OK, I have another workaround:  use the new LLJit instead of the old (default) MCJit.  To do this, just include this somewhere early on:

#include "rrConfig.h"

Config::setValue(Config::LLVM_BACKEND, Config::LLVM_BACKEND_VALUES::LLJIT);

For me, this fixes the code you've posted.  It also makes sense, since the LLVM code is where the problems seem to be arising, and both sets of code are basically completely separate.

**Comment by steffenger** [comment] 2022-03-25 09:10
@luciansmith thank you very much:)

**Comment by CiaranWelsh** [comment] 2022-03-25 19:54
The LLJit also has the added benefit of being faster too. It should become the default in a future release.

I’ll take a look and see if I can find a fix.

**Comment by luciansmith** [comment] 2022-03-29 23:53
Ciaran came up with a solution that should work even with the original MCJit which passes the tests, including my copy of your code above.  If you're happy with the LLJit solution, that's fine, but if you want to switch back for any reason, it should now work, and will be included in the next release!

**Closed as completed** 2022-04-04 06:56 UTC
