### ISSUE TITLE
Figure out stochastic slowdowns

### ISSUE THREAD

**Issue by luciansmith** [sys-bio/roadrunner#929] opened 2021-12-13 23:49 UTC
Switching linux VMs ended up severely slowing down the stochastic tests (by maybe 10-fold) and we should investigate why this is, and if we can get the new VM to go any faster.

Also, tests 5 and 23 take a really long time to run, for unclear reasons.

**Comment by CiaranWelsh** [comment] 2022-01-07 11:19
closing this issue as its duplicate of #939 which has slightly more information.

**Closed as completed by CiaranWelsh** 2022-01-07 11:19 UTC
