### ISSUE TITLE
C API: getRatesOfChangeIds should return all floating species Ids. 

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#1011] opened 2022-05-24 21:53 UTC
Currently, getRatesOfChangeIds only returns the ids for the independent species. It should however return all floating species Ids. 

(Note it doesn't return the rate rule ids, do we want it to do that, or add another method for those?)

**Comment by luciansmith** [comment] 2022-05-24 22:36
getRatesOfChangeIds should return the Ids of the elements returned by getRatesOfChange, which currently only returns the independent species rates of change.

We can have other function pairs for other groups of elements.

**Comment by hsauro** [comment] 2022-05-24 22:42
I'm not sure what this file does, rrc_api_cdecl.def,  (it may be a file for VS) but it might (or might not) need to be updated when new methods are added

**Comment by luciansmith** [comment] 2022-05-24 22:52
I'm closing this, since it must match.  (also, a duplicate of https://github.com/sys-bio/roadrunner/issues/1009)

**Closed as completed by luciansmith** 2022-05-24 22:52 UTC
