### ISSUE TITLE
Different trajectories for equivalent models using gillespie integrator

### ISSUE THREAD

**Issue by leon9812** [sys-bio/roadrunner#1135] opened 2023-06-13 11:00 UTC
The following two models should produce the same trajectories, but only `r1` yields the expected results.
```python
import tellurium as te
r1 = te.loada("""
   S1 => 2 S2; c1*S1
   S1 = 100; c1 = 1.0
""")
r2 = te.loada("""
   S1 => S2 + S2; c1*S1
   S1 = 100; c1 = 1.0
""")

def simulate(r):
    r.integrator = "gillespie"
    r.integrator.seed = 0
    return r.simulate(0, 2)

s1 = simulate(r1)
s2 = simulate(r2)

import matplotlib.pyplot as plt
plt.plot(s1["time"], s1["[S1]"], label="r1-S1")
plt.plot(s2["time"], s2["[S1]"], label="r2-S1", linestyle="dashed")
plt.plot(s1["time"], s1["[S2]"], label="r1-S2")
plt.plot(s2["time"], s2["[S2]"], label="r2-S2", linestyle="dashed")
plt.legend()
plt.show()
```
trajectories:
![trajectories](https://github.com/sys-bio/roadrunner/assets/50578381/b4255cb1-499e-4021-a6bf-71b112f2b0bb)

**Comment by luciansmith** [comment] 2023-06-13 16:09
Thanks for the report!  I'll investigate.

I will note that the problem is not, as I first thought, that the seed does different things in the two models.  The problem is that the gillespie integrator doesn't handle 'S1 + S1' correctly.

**Comment by luciansmith** [comment] 2023-11-02 21:37
This is now fixed!  It should be included in the next roadrunner release.  Thank you again for the report!

**Closed as completed by luciansmith** 2023-11-02 21:37 UTC
