### ISSUE TITLE
`Selections` method might benefit from backwards compatibility

### ISSUE THREAD

**Issue by kirichoi** [sys-bio/roadrunner#220] opened 2015-10-14 18:14 UTC
Suggestion from @matthiaskoenig:

Might want to parse `selections` to `timeCourseSelections` for backwards compatibility.

Should work since we did not assign anything for `selections` for now. Any thoughts?

**Comment by 0u812** [comment] 2015-10-14 19:41
Need more detail

**Comment by hsauro** [comment] 2015-10-14 19:57
We could do that but at at version 2.0 we remove it. This should be
indicated in the online docs.

Herbert

**Comment by 0u812** [comment] 2015-10-14 19:59
duplicate of #218

**Closed by 0u812** 2015-10-14 19:59 UTC
Labels: enhancement
