### ISSUE TITLE
Using output_file results in "IndexError: index -1 is out of bounds for axis 0 with size 0"

### ISSUE THREAD

**Issue by UnkindPartition** [sys-bio/roadrunner#965] opened 2022-02-21 08:12 UTC
Hi,

This code works for me and prints the result matrix:

``` python
from roadrunner import RoadRunner
r = RoadRunner("sbml_model.xml")
print(r.simulate(0, 100, 1001))
```

If I add an `output_file` option, however

``` python
from roadrunner import RoadRunner
r = RoadRunner("sbml_model.xml")
r.simulate(0, 100, 1001, output_file = "out.csv")
```

it fails with

```
Traceback (most recent call last):
  File "simulate_with_roadrunner.py", line 12, in <module>
    print(r.simulate(0, 100, 1001, output_file = output_file))
  File "/nix/store/lvjrz89l17sn54pnb2fm7sdxcn3ab3wr-python3-3.9.6-env/lib/python3.9/site-packages/roadrunner/roadrunner.py", line 4611, in simulate
    lastresult_time = result[len(result)-1][selections_lower.index("time")]
IndexError: index -1 is out of bounds for axis 0 with size 0
```

This is with libroadrunner 2.2.0. Interestingly, with libroadrunner 2.1.3 the above also failed, but I could it get it working by using positional arguments instead of named ones:

``` python
from roadrunner import RoadRunner
r = RoadRunner("sbml_model.xml")
r.simulate(0, 100, 1001, ["time", "rate"], "out.csv")
```

With 2.2.0, however, this doesn't work either.

[sbml_model.xml](https://github.com/sys-bio/roadrunner/files/8107350/sbml_model.txt) (need to manually rename from .txt to .xml as github doesn't allow uploading xmls)

**Comment by luciansmith** [comment] 2022-02-23 01:27
Thanks for the report!  I'm able to reproduce the error, and am looking into a solution.

**Comment by luciansmith** [comment] 2022-02-23 22:43
OK, this is now fixed!  The issue is that a new check was added to the source that looked at the results, without remembering that when writing to a file, 'results' was empty.

You can get new wheels to test things out yourself at

https://dev.azure.com/TheRoadrunnerProject/roadrunner/_build/results?buildId=1504&view=artifacts&pathAsName=false&type=publishedArtifacts

for your system, and the next release of roadrunner will contain the fix as well.  If you want to edit the code yourself, it's a simple fix:  one block of code is moved lower in the file in a new 'else' block.  The changes can be found at https://github.com/sys-bio/roadrunner/commit/50632014a0de4564ddbf3397dc6372545d521de9

Do let us know if you need any other information or help!

**Comment by UnkindPartition** [comment] 2022-02-24 20:32
Thank you for the fast fix, Lucian!

**Comment by luciansmith** [comment] 2022-02-24 21:01
Glad it's working!

**Closed as completed by luciansmith** 2022-02-24 21:01 UTC
