### ISSUE TITLE
SBML L1V2 model problem with amounts/concentrations

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#371] opened 2017-05-11 14:52 UTC
Hi all,
I was just reading the recent LASSIE paper (see
https://github.com/matthiaskoenig/lassie-test/blob/master/docs/LASSIE-simulating.large-scale.models.of.biochemical.networks_Tangherloni2017.pdf)
were they implemented some Mass-Action Kinetics solver on GPUs.

They make a performance comparison against LSODA and I wanted to test their large-scale model with roadrunner (SBML file here:
https://github.com/matthiaskoenig/lassie-test/blob/master/models/copasi_test_4096x4096.xml)

When running the simulations I get negative concentrations and the integration aborts. The reason is that roadrunner handles the ODEs via concentrations and not amounts and in the SBML are many kinetic laws of the form
```
		<reaction name="R2062" reversible="false">
			<listOfReactants>
			<speciesReference species="X2659" stoichiometry="2"/>
			</listOfReactants>
			<kineticLaw formula="K2062* (1/2) * X2659* (X2659-1)">
				<listOfParameters>
					<parameter name="K2062" value="3.615465778822864E-4"/>
				</listOfParameters>
			</kineticLaw>
		</reaction>
```
With the `X2659* (X2659-1)` terms only working when treating species as amounts.

So how can I simulate this valid SBML model with amounts and not concentrations in roadrunner. This is a L1V2 SBML file and not sure what the specifications says here, but there is no field `hasOnlySubstanceUnits` which I would normally use to encode either amount or concentration information.

complete repository with test code and example here:
https://github.com/matthiaskoenig/lassie-test

Matthias

**Comment by hsauro** [comment] 2017-05-11 15:52
Are you asking how can be specifiy amounts rather than concentration in an
SBML file? Or are you asking whether libRoadRunner can read in amounts from
the SBML rather than concentration? I thought it did already did do this
but perhaps not.

Kyle, any comments?

Herbert

**Comment by luciansmith** [comment] 2017-05-11 16:06
I have a theory!

I would guess that what is happening is that libroadrunner is assuming that 'hasOnlySubstanceUnits' is always set and always has a value.  However, this turns out to not be the case in l2v1 models, so what needs to be done is to change code that I assume lives somewhere in libroadrunner's innards from:

bool hosu = species->getHasOnlySubstanceUnits()

to:

bool hosu = true
if (species->isSetHasOnlySubstanceUnits()) {
  hosu = species->getHasOnlySubstanceUnits()
}

**Comment by hsauro** [comment] 2017-05-11 16:16
Kyle, what do you think?

Herbert

**Comment by luciansmith** [comment] 2017-05-11 16:47
One thing that could be done to check this and other issues with earlier versions of SBML is to run the test suite on *all* levels and versions provided, not just the most recent.  That will test the assumptions and defaults of earlier level/versions that were made explicit in later ones.  I *think* doing that would have caught this particular problem, at least.  It does take a lot more time to run the tests, of course.

**Comment by matthiaskoenig** [comment] 2017-05-11 17:49
How could I run the given L1V2 file with roadrunner? Or is the only way to
run with amounts to convert to higher SBML level/versions and set
hasOnlySubstance units ?

**Comment by hsauro** [comment] 2017-05-11 17:55
Would using the libsbml converter help? Covert to say L2V4?

Herbert

**Comment by 0u812** [comment] 2017-05-11 19:10
Lucian is right that the current code doesn't check `isSetHasOnlySubstanceUnits`. I'll try to fix this and see if it fixes the simulation.

**Comment by 0u812** [comment] 2017-05-11 20:47
Btw it looks like when `isSetHasOnlySubstanceUnits` returns false, we want to assume that `hasOnlySubstanceUnits` should be true. Please let me know if that assumption is wrong.

**Comment by luciansmith** [comment] 2017-05-11 21:01
OK, I looked into this, and it turns out that in SBML Level 1, species were assumed to always have units of *concentration*, not amount.  Here's the message I get when I translate an L2 substance-only species to L1:

"The concept of a Species having only substance units and not units of concentration cannot be correctly interpreted in SBML Level 1 without alteration of any mathematical formula. LibSBML does not do this alteration."

So I would say that either the original model is incorrect in this case, or Matthias is incorrect in his assumption of why the model is not simulating correctly.  It is definitely the case that all of the species IDs used in any SBML L1 formula are assumed to have units of concentration.

So my pseudocode was incorrect--hasOnlySubstanceUnits should be assumed to be 'false' if not set.

(It's probably worth making that change to libroadrunner, just to make it explicit.  'hasOnlySubstanceUnits' probably defaults to 'false' in the libsbml code, but it's generally unwise to use unset values.  But it won't fix Matthias's problem in this case.)

There may be some other assumption going on here--Matthias, if you can translate the model to l2v4 and re-simulate, if you get the same results, that means that either the model is wrong or something else is going wrong.  I might also try translating to l2v4 and then manually changing all the hosu attributes to 'true' to see if that fixes it.  If so, that would confirm that the original model is incorrect.

**Comment by 0u812** [comment] 2017-05-11 23:03
Thanks Lucian!

**Comment by matthiaskoenig** [comment] 2017-05-12 10:40
Hi Lucian et al, 

thanks for the information. I did not know how amount/concentrations was handled in L1V2.
So roadrunner works correctly, but the model encoding is incorrect. This is the main information I needed.

I reported the issues with the SBML file to the developers of LASSIE, which have to fix the SBML model
https://github.com/aresio/LASSIE/issues/1
In addition I asked for the other models as SBML which they use in their performance tests, so I can test the roadrunner performance against the GPU approach (for mass-action models).

I hope they fix the SBML, otherwise I would try to fix it by an upconversion to L3V1 with libsbml and setting the hasOnlySubstanceUnits manually.

Thanks again.

**Comment by luciansmith** [comment] 2017-05-12 19:43
OK, I thought of something to check:  the compartment size is not set in the document, which means that it will default to 1.  This means that it doesn't matter if the model is set in terms of units or amounts; numerically, it will be numerically identical.  The units will be off, but that won't make the numbers go negative or anything like that.

This means that something else is going wrong, and that the problem is not the hasOnlySubstanceUnits issue.  Unfortunately, I don't know what that problem might be.

**Comment by hsauro** [comment] 2017-05-12 19:45
Yes that could be true. Kyle what the status of the fix, did you try the
fix?

Herbert

**Comment by matthiaskoenig** [comment] 2017-05-14 12:02
Yes, it's a combination of problems.
On the model the initial values on the species are set via `initialAmount`, e.g.
<species id=X2659 initialAmount=0.8 ...>
Which is probably the concentration and due to volume of compartment = 1 also the amount (probably in mole). What they need is items (i.e. multiply with avogadro constant).

The initialAmounts of 0.8 (mole?) are of course not working together with the kineticLaws of:
kineticLaw formula="K2062* (1/2) * X2659* (X2659-1)"

So this is definitively a incorrect encoded SBML model. This is especially bad, because they write in the publication

> In addition, COPASI fails when trying to
simulate large-scale models. We provide an example of
such model—characterized by 4096 reactions and 4096
species—as SBML file in the GITHUB repository.

COPASI has the ability to convert from mole to items, but I am not sure if the integration failed because the model was so large or wrongly encoded. COPASI is normally able to deal with such large models (takes just forever to load the model in the GUI, and the integration is quit slow).

This was also the reason why I wanted to try with libroadrunner, because I am sure that such large models are no problem (and I am working with quit large models on a daily basis, ~2000 reactions and species)

**Comment by luciansmith** [comment] 2021-09-21 17:20
It looks to me like this issue was in the encoding of the model in question, but that roadrunner was indeed interpreting it correctly.  I'm closing this, but if I'm wrong, please re-open.  Thank you!

**Closed as completed by luciansmith** 2021-09-21 17:20 UTC
