### ISSUE TITLE
roadrunner instances should be pickelable

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#747] opened 2021-04-17 23:05 UTC
roadrunner instances should be pickelable. This would allow roadrunner to be used with the multuprocessing package and make roadrunner run more easily parallizable. 

Use roadrunner methods saveState and loadState to override pickle system.

This is also a request from Matthias.

**Comment by matthiaskoenig** [comment] 2021-04-18 09:19
Duplicate of #743. Some additional information in the other issue.

**Comment by CiaranWelsh** [comment] 2021-09-20 09:01
closing in favour of #743

**Closed as completed by CiaranWelsh** 2021-09-20 09:01 UTC
Labels: duplicate, enhancement
