### ISSUE TITLE
SBML string is parsed into SBMLDocument multiple times per model load

### ISSUE THREAD

**Issue by CiaranWelsh** [sys-bio/roadrunner#921] opened 2021-11-30 16:16 UTC
When reading from sbml, the call to `libsbml::readSBMLFromString` is made [3 times ](https://github.com/sys-bio/roadrunner/issues/899#issuecomment-982493522) (at least). 

1) In the call to fixMissingStoicAndMath. 
2) When creating the ModelGeneratorContext. 
3) reading the SBMLDocument into impl->document (RoadRunner::load)

Given that it is an expensive operation to parse sbml from string, modifying roadrunner such that this only happens once per model load may shave some time off of roadrunner build time.

**Comment by luciansmith** [comment] 2021-11-30 17:31
I'm happy to take this one--I feel confident that I can figure out what we were doing and find a different method for it.  Thanks for profiling things so that we know where to optimize!

**Comment by CiaranWelsh** [comment] 2021-11-30 19:54
Okay cool - I thought you might. But we may need to come together to resolve some merge conflicts when the time comes. I also noticed that there are a few additional sbml writes that could be optimized if we return a SBMLDocument instead of a string.

**Comment by luciansmith** [comment] 2021-12-01 04:36
This is now done, barring https://github.com/sys-bio/roadrunner/issues/924.  Once you run your profiler again to ensure that the problem is indeed dealt with, we can close this issue (no rush).

**Closed as completed** 2022-01-07 12:06 UTC
